"""Reference CSR Transformer training export path for external checkpoints."""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from transsolvestack.policies.csr_external_model_adapter import (
    CSR_EXTERNAL_MODEL_ADAPTER_SCHEMA_VERSION,
    CSR_EXTERNAL_RANKER_CHECKPOINT_SCHEMA_VERSION,
    CSR_EXTERNAL_RANKER_ADAPTER,
    adapt_csr_external_ranker_checkpoint_from_files,
    build_reference_csr_external_ranker_checkpoint_from_files,
    write_csr_external_model_adapter_model,
    write_csr_external_model_adapter_predictions,
    write_csr_external_model_adapter_ranker_summary,
    write_csr_external_model_adapter_report,
    write_csr_external_model_adapter_rows,
    write_csr_external_model_adapter_schema,
    write_csr_external_model_adapter_summary,
    write_csr_external_ranker_checkpoint,
)
from transsolvestack.policies.csr_transformer_ranker import (
    train_csr_transformer_ranker_from_tensor_file,
    write_csr_transformer_ranker_model,
    write_csr_transformer_ranker_predictions,
    write_csr_transformer_ranker_report,
    write_csr_transformer_ranker_schema,
    write_csr_transformer_ranker_summary,
)
from transsolvestack.profiling.artifacts import write_jsonl


CSR_TRANSFORMER_REFERENCE_TRAINING_EXPORT_SCHEMA_VERSION = (
    "phase1_csr_transformer_reference_training_export_v1"
)


def build_csr_transformer_reference_training_export_from_files(
    tensor_path: str | Path = (
        "runs/phase1_csr_transformer_ready/csr_transformer_training_tensors.json"
    ),
    request_index_path: str | Path = (
        "runs/phase1_csr_transformer_ready/csr_transformer_request_index.jsonl"
    ),
    training_entrypoint_summary_path: str | Path = (
        "runs/phase1_csr_transformer_training_entrypoint/"
        "csr_transformer_training_entrypoint_summary.json"
    ),
    output_dir: str | Path = "runs/phase1_csr_transformer_reference_training_export",
    *,
    contributor_id: str = "wei_cui_reference",
    contributor_name: str = "Wei CUI",
    model_id: str = "csr_masked_self_attention_ranker_v1",
    d_model: int = 24,
    num_attention_heads: int = 4,
    feedforward_dim: int = 48,
    epochs: int = 160,
    learning_rate: float = 0.03,
    l2_regularization: float = 1.0e-4,
    seed: int = 18,
) -> dict[str, Any]:
    """Train the local reference ranker and export an intake-ready checkpoint.

    This is a lightweight reference path for contributors and CI. It does not
    promote a learned policy into runtime. Its purpose is to prove that a
    trained CSR Transformer-style ranker can be serialized into the external
    checkpoint schema consumed by the adapter and intake runner.
    """

    tensor_path = Path(tensor_path)
    request_index_path = Path(request_index_path)
    training_entrypoint_summary_path = Path(training_entrypoint_summary_path)
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    paths = _paths(output)

    training_entrypoint = _read_json(training_entrypoint_summary_path)
    export = train_csr_transformer_ranker_from_tensor_file(
        tensor_path,
        request_index_path,
        model_id=model_id,
        d_model=d_model,
        num_attention_heads=num_attention_heads,
        feedforward_dim=feedforward_dim,
        epochs=epochs,
        learning_rate=learning_rate,
        l2_regularization=l2_regularization,
        seed=seed,
    )
    write_csr_transformer_ranker_model(export.model, paths["model"])
    write_csr_transformer_ranker_predictions(export.predictions, paths["predictions"])
    write_csr_transformer_ranker_summary(export.summary, paths["ranker_summary"])
    write_csr_transformer_ranker_schema(export.schema, paths["ranker_schema"])
    write_csr_transformer_ranker_report(export, paths["ranker_report"])

    checkpoint = build_reference_csr_external_ranker_checkpoint_from_files(
        paths["model"],
        tensor_path,
        request_index_path,
        contributor_id=contributor_id,
        contributor_name=contributor_name,
        training_statement=(
            "Reference CSR Transformer training export generated by "
            "TransSolveStack's local masked self-attention ranker."
        ),
    )
    write_csr_external_ranker_checkpoint(checkpoint, paths["checkpoint"])

    adapter = adapt_csr_external_ranker_checkpoint_from_files(
        paths["checkpoint"],
        tensor_path,
        request_index_path,
    )
    _write_adapter(adapter, paths)

    validation_errors = _validation_errors(
        training_entrypoint=training_entrypoint,
        export_summary=asdict(export.summary),
        adapter_summary=adapter["summary"],
        model=export.model,
        adapted_model=adapter["adapted_model"],
        predictions=_prediction_rows(export.predictions),
        adapted_predictions=_prediction_rows(adapter["predictions"]),
    )
    summary = _summary(
        training_entrypoint=training_entrypoint,
        export_summary=asdict(export.summary),
        adapter_summary=adapter["summary"],
        validation_errors=validation_errors,
        paths=paths,
    )
    schema = _schema(summary)
    rows = _rows(summary)
    report = _report(summary)
    _write_json(summary, paths["summary"])
    _write_json(schema, paths["schema"])
    write_jsonl(rows, paths["rows"])
    paths["report"].write_text(report, encoding="utf-8")
    return {
        "paths": {key: str(value) for key, value in paths.items()},
        "summary": summary,
        "schema": schema,
        "rows": rows,
        "report": report,
        "ranker_export": export,
        "checkpoint": checkpoint,
        "adapter": adapter,
    }


def _paths(output: Path) -> dict[str, Path]:
    return {
        "model": output / "reference_csr_transformer_ranker_model.json",
        "predictions": output / "reference_csr_transformer_ranker_predictions.jsonl",
        "ranker_summary": output / "reference_csr_transformer_ranker_summary.json",
        "ranker_schema": output / "reference_csr_transformer_ranker_schema.json",
        "ranker_report": output / "reference_csr_transformer_ranker_report.md",
        "checkpoint": output / "reference_csr_external_ranker_checkpoint.json",
        "adapted_model": output / "reference_csr_external_adapter_model.json",
        "adapted_predictions": (
            output / "reference_csr_external_adapter_predictions.jsonl"
        ),
        "adapted_ranker_summary": (
            output / "reference_csr_external_adapter_ranker_summary.json"
        ),
        "adapter_rows": output / "reference_csr_external_adapter_rows.jsonl",
        "adapter_summary": output / "reference_csr_external_adapter_summary.json",
        "adapter_schema": output / "reference_csr_external_adapter_schema.json",
        "adapter_report": output / "reference_csr_external_adapter_report.md",
        "rows": output / "csr_transformer_reference_training_export_rows.jsonl",
        "summary": output / "csr_transformer_reference_training_export_summary.json",
        "schema": output / "csr_transformer_reference_training_export_schema.json",
        "report": output / "csr_transformer_reference_training_export_report.md",
    }


def _write_adapter(data: dict[str, Any], paths: dict[str, Path]) -> None:
    write_csr_external_model_adapter_model(data, paths["adapted_model"])
    write_csr_external_model_adapter_predictions(
        data["predictions"],
        paths["adapted_predictions"],
    )
    write_csr_external_model_adapter_ranker_summary(
        data,
        paths["adapted_ranker_summary"],
    )
    write_csr_external_model_adapter_rows(data["rows"], paths["adapter_rows"])
    write_csr_external_model_adapter_summary(data, paths["adapter_summary"])
    write_csr_external_model_adapter_schema(data, paths["adapter_schema"])
    write_csr_external_model_adapter_report(data, paths["adapter_report"])


def _validation_errors(
    *,
    training_entrypoint: dict[str, Any],
    export_summary: dict[str, Any],
    adapter_summary: dict[str, Any],
    model: dict[str, Any],
    adapted_model: dict[str, Any],
    predictions: tuple[dict[str, Any], ...],
    adapted_predictions: tuple[dict[str, Any], ...],
) -> tuple[str, ...]:
    errors: list[str] = []
    if training_entrypoint.get("status") != "passed":
        errors.append("training_entrypoint_not_passed")
    if training_entrypoint.get("training_entrypoint_ready") is not True:
        errors.append("training_entrypoint_not_ready")
    if training_entrypoint.get("runtime_selector_changed") is not False:
        errors.append("training_entrypoint_changed_runtime_selector")
    if export_summary.get("status") != "passed":
        errors.append("reference_ranker_not_passed")
    if export_summary.get("model_trained") is not True:
        errors.append("reference_ranker_not_trained")
    if export_summary.get("runtime_selector_changed") is not False:
        errors.append("reference_ranker_changed_runtime_selector")
    if adapter_summary.get("adapter_ready") is not True:
        errors.append("adapter_not_ready")
    if adapter_summary.get("prediction_contract_valid") is not True:
        errors.append("adapter_prediction_contract_invalid")
    if adapter_summary.get("runtime_selector_changed") is not False:
        errors.append("adapter_changed_runtime_selector")
    if model != adapted_model:
        errors.append("adapter_model_roundtrip_mismatch")
    if predictions != adapted_predictions:
        errors.append("adapter_prediction_roundtrip_mismatch")
    return tuple(errors)


def _summary(
    *,
    training_entrypoint: dict[str, Any],
    export_summary: dict[str, Any],
    adapter_summary: dict[str, Any],
    validation_errors: tuple[str, ...],
    paths: dict[str, Path],
) -> dict[str, Any]:
    export_ready = not validation_errors
    return {
        "status": "passed" if export_ready else "failed",
        "schema_version": CSR_TRANSFORMER_REFERENCE_TRAINING_EXPORT_SCHEMA_VERSION,
        "reference_training_export_ready": export_ready,
        "model_training_executed": True,
        "model_trained": bool(export_summary["model_trained"]),
        "training_entrypoint_ready": bool(
            training_entrypoint.get("training_entrypoint_ready")
        ),
        "external_checkpoint_ready": (
            adapter_summary.get("checkpoint_schema_version")
            == CSR_EXTERNAL_RANKER_CHECKPOINT_SCHEMA_VERSION
        ),
        "checkpoint_schema_version": CSR_EXTERNAL_RANKER_CHECKPOINT_SCHEMA_VERSION,
        "adapter": CSR_EXTERNAL_RANKER_ADAPTER,
        "adapter_schema_version": CSR_EXTERNAL_MODEL_ADAPTER_SCHEMA_VERSION,
        "adapter_ready": bool(adapter_summary["adapter_ready"]),
        "adapter_roundtrip_exact": "adapter_model_roundtrip_mismatch"
        not in validation_errors
        and "adapter_prediction_roundtrip_mismatch" not in validation_errors,
        "intake_input_ready": export_ready,
        "quality_gate_required": True,
        "current_quality_gate_runtime_eligible": bool(
            training_entrypoint.get("current_quality_gate_runtime_eligible")
        ),
        "default_runtime_mode": "shadow",
        "runtime_selector_changed": False,
        "model_id": export_summary["model_id"],
        "model_family": export_summary["model_family"],
        "encoder_training": export_summary["encoder_training"],
        "num_predictions": int(export_summary["num_predictions"]),
        "num_eval_predictions": int(export_summary["num_eval_requests"]),
        "num_eval_oracle_requests": int(export_summary["num_eval_oracle_requests"]),
        "d_model": int(export_summary["d_model"]),
        "num_attention_heads": int(export_summary["num_attention_heads"]),
        "feedforward_dim": int(export_summary["feedforward_dim"]),
        "num_epochs": int(export_summary["num_epochs"]),
        "eval_oracle_top1_accuracy": float(
            export_summary["eval_oracle_top1_accuracy"]
        ),
        "eval_profiled_success_selection_rate": float(
            export_summary["eval_profiled_success_selection_rate"]
        ),
        "eval_non_success_selection_count": int(
            export_summary["eval_non_success_selection_count"]
        ),
        "validation_error_count": len(validation_errors),
        "validation_errors": validation_errors,
        "artifact_paths": {
            "model": str(paths["model"]),
            "predictions": str(paths["predictions"]),
            "checkpoint": str(paths["checkpoint"]),
            "adapter_summary": str(paths["adapter_summary"]),
            "intake_command_input": str(paths["checkpoint"]),
        },
        "next_step": "submit_checkpoint_to_external_model_intake",
    }


def _rows(summary: dict[str, Any]) -> tuple[dict[str, Any], ...]:
    schema = summary["schema_version"]
    return (
        {
            "schema_version": schema,
            "row_kind": "training_result",
            "model_id": summary["model_id"],
            "model_trained": summary["model_trained"],
            "num_predictions": summary["num_predictions"],
        },
        {
            "schema_version": schema,
            "row_kind": "external_checkpoint",
            "checkpoint_schema_version": summary["checkpoint_schema_version"],
            "adapter": summary["adapter"],
            "checkpoint_ready": summary["external_checkpoint_ready"],
        },
        {
            "schema_version": schema,
            "row_kind": "adapter_roundtrip",
            "adapter_ready": summary["adapter_ready"],
            "adapter_roundtrip_exact": summary["adapter_roundtrip_exact"],
        },
        {
            "schema_version": schema,
            "row_kind": "intake_boundary",
            "intake_input_ready": summary["intake_input_ready"],
            "default_runtime_mode": summary["default_runtime_mode"],
            "quality_gate_required": summary["quality_gate_required"],
        },
        {
            "schema_version": schema,
            "row_kind": "runtime_boundary",
            "runtime_selector_changed": summary["runtime_selector_changed"],
            "current_quality_gate_runtime_eligible": summary[
                "current_quality_gate_runtime_eligible"
            ],
        },
        {
            "schema_version": schema,
            "row_kind": "export_decision",
            "status": summary["status"],
            "reference_training_export_ready": summary[
                "reference_training_export_ready"
            ],
            "validation_errors": summary["validation_errors"],
        },
    )


def _schema(summary: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": summary["schema_version"],
        "task": "export_reference_transformer_training_checkpoint",
        "outputs": {
            "model": summary["artifact_paths"]["model"],
            "predictions": summary["artifact_paths"]["predictions"],
            "checkpoint": summary["artifact_paths"]["checkpoint"],
            "adapter_summary": summary["artifact_paths"]["adapter_summary"],
        },
        "checkpoint_contract": {
            "schema_version": CSR_EXTERNAL_RANKER_CHECKPOINT_SCHEMA_VERSION,
            "adapter": CSR_EXTERNAL_RANKER_ADAPTER,
            "intake_input_ready": summary["intake_input_ready"],
        },
        "runtime_boundary": {
            "default_mode": "shadow",
            "quality_gate_required": True,
            "runtime_selector_changed": False,
            "automatic_runtime_promotion": False,
        },
    }


def _report(summary: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# CSR Transformer Reference Training Export",
            "",
            f"- status: `{summary['status']}`",
            f"- schema_version: `{summary['schema_version']}`",
            f"- reference_training_export_ready: `{summary['reference_training_export_ready']}`",
            f"- model_trained: `{summary['model_trained']}`",
            f"- external_checkpoint_ready: `{summary['external_checkpoint_ready']}`",
            f"- adapter_ready: `{summary['adapter_ready']}`",
            f"- adapter_roundtrip_exact: `{summary['adapter_roundtrip_exact']}`",
            f"- intake_input_ready: `{summary['intake_input_ready']}`",
            f"- default_runtime_mode: `{summary['default_runtime_mode']}`",
            f"- quality_gate_required: `{summary['quality_gate_required']}`",
            f"- runtime_selector_changed: `{summary['runtime_selector_changed']}`",
            f"- model_id: `{summary['model_id']}`",
            f"- eval_oracle_top1_accuracy: `{summary['eval_oracle_top1_accuracy']:.6g}`",
            f"- eval_profiled_success_selection_rate: `{summary['eval_profiled_success_selection_rate']:.6g}`",
            f"- eval_non_success_selection_count: `{summary['eval_non_success_selection_count']}`",
            f"- validation_error_count: `{summary['validation_error_count']}`",
            "",
            "## Intake Input",
            "",
            f"- checkpoint: `{summary['artifact_paths']['checkpoint']}`",
            "",
        ]
    )


def _prediction_rows(predictions: Any) -> tuple[dict[str, Any], ...]:
    return tuple(asdict(row) for row in predictions)


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(data: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path
