"""TransSolveStack public package."""

from transsolvestack.core.types import (
    ImplicitSolveContext,
    LinearOperatorSpec,
    LinearSystem,
    SolveContext,
)
from transsolvestack.core.result import PolicyPlan, RunTrace, SolveResult
from transsolvestack.api import (
    accept_csr_policy_model_artifact,
    adapt_csr_external_ranker_checkpoint,
    auto_solve,
    auto_solve_csr,
    auto_solve_csr_guarded,
    build_csr_policy_model_artifact,
    build_reference_csr_external_ranker_checkpoint,
    build_csr_transformer_reference_training_export,
    build_csr_transformer_training_entrypoint,
    build_suitesparse_index,
    build_csr_transformer_ready_bundle,
    diagnose_csr_matrix,
    evaluate_csr_selector_models,
    export_csr_learning_rows,
    export_csr_model_contract,
    export_csr_selector_rows,
    export_csr_training_tensors,
    export_policy_training_rows,
    import_suitesparse_csr,
    plan,
    plan_csr_benchmark_expansion,
    plan_csr_full_dataset_queue,
    plan_csr,
    plan_csr_with_learned_guard,
    plan_dataset_downloads,
    prepare_csr_policy_model_submission,
    probe_suitesparse_headers,
    run_csr_external_model_intake,
    select_suitesparse_subset,
    solve,
    solve_csr,
    train_csr_linear_ranker,
    train_csr_transformer_ranker,
)
from transsolvestack.datasets.selection import MatrixSelectionCriteria
from transsolvestack.datasets.diagnostics import CsrMatrixDiagnostic

__all__ = [
    "CsrMatrixDiagnostic",
    "ImplicitSolveContext",
    "LinearOperatorSpec",
    "LinearSystem",
    "MatrixSelectionCriteria",
    "PolicyPlan",
    "RunTrace",
    "SolveContext",
    "SolveResult",
    "accept_csr_policy_model_artifact",
    "adapt_csr_external_ranker_checkpoint",
    "auto_solve",
    "auto_solve_csr",
    "auto_solve_csr_guarded",
    "build_csr_policy_model_artifact",
    "build_reference_csr_external_ranker_checkpoint",
    "build_csr_transformer_reference_training_export",
    "build_csr_transformer_training_entrypoint",
    "build_suitesparse_index",
    "build_csr_transformer_ready_bundle",
    "diagnose_csr_matrix",
    "evaluate_csr_selector_models",
    "export_csr_learning_rows",
    "export_csr_model_contract",
    "export_csr_selector_rows",
    "export_csr_training_tensors",
    "export_policy_training_rows",
    "import_suitesparse_csr",
    "plan",
    "plan_csr_benchmark_expansion",
    "plan_csr_full_dataset_queue",
    "plan_csr",
    "plan_csr_with_learned_guard",
    "plan_dataset_downloads",
    "prepare_csr_policy_model_submission",
    "probe_suitesparse_headers",
    "run_csr_external_model_intake",
    "select_suitesparse_subset",
    "solve",
    "solve_csr",
    "train_csr_linear_ranker",
    "train_csr_transformer_ranker",
]
